CREATE TABLE Data_table (
    ID INT PRIMARY KEY, 
    DATE_OF_PREDICTION DATE,
    NAME_INCOME_TYPE VARCHAR(255),
    NAME_EDUCATION_TYPE VARCHAR(255),
    NAME_HOUSING_TYPE VARCHAR(255),
    OCCUPATION_TYPE VARCHAR(255),
    AMT_INCOME_TOTAL VARCHAR(255),
    DAYS_EMPLOYED VARCHAR(255),
    FLAG_OWN_CAR VARCHAR(255),
    FLAG_OWN_REALITY VARCHAR(255)
);
